const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, '../data/nouns.json');
const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
const existingWords = new Set(data.words.map(w => w.word.toLowerCase()));
console.log('현재 명사 수:', existingWords.size);

const finalNouns = [
  // 최종 추가 명사들 (180개)
  { word: "corruption", meaning: "부패" },
  { word: "coverage", meaning: "보도범위" },
  { word: "creation", meaning: "창조" },
  { word: "creativity", meaning: "창의성" },
  { word: "creditor", meaning: "채권자" },
  { word: "crisis", meaning: "위기" },
  { word: "criticism", meaning: "비판" },
  { word: "cultivation", meaning: "재배" },
  { word: "curiosity", meaning: "호기심" },
  { word: "custody", meaning: "보관" },
  { word: "customization", meaning: "맞춤화" },
  { word: "deadline", meaning: "마감일" },
  { word: "debate", meaning: "토론" },
  { word: "debtor", meaning: "채무자" },
  { word: "declaration", meaning: "선언" },
  { word: "decline", meaning: "감소" },
  { word: "decoration", meaning: "장식" },
  { word: "dedication", meaning: "헌신" },
  { word: "deduction", meaning: "공제" },
  { word: "defect", meaning: "결함" },
  { word: "defender", meaning: "수비수" },
  { word: "definition", meaning: "정의" },
  { word: "delegation", meaning: "대표단" },
  { word: "deliberation", meaning: "숙고" },
  { word: "delivery", meaning: "배달" },
  { word: "denial", meaning: "부정" },
  { word: "departure", meaning: "출발" },
  { word: "dependence", meaning: "의존" },
  { word: "deployment", meaning: "배치" },
  { word: "depression", meaning: "우울증" },
  { word: "description", meaning: "설명" },
  { word: "designation", meaning: "지정" },
  { word: "despair", meaning: "절망" },
  { word: "destination", meaning: "목적지" },
  { word: "destruction", meaning: "파괴" },
  { word: "detection", meaning: "탐지" },
  { word: "determination", meaning: "결심" },
  { word: "development", meaning: "개발" },
  { word: "devotion", meaning: "헌신" },
  { word: "diagnosis", meaning: "진단" },
  { word: "dialogue", meaning: "대화" },
  { word: "differentiation", meaning: "차별화" },
  { word: "dimension", meaning: "차원" },
  { word: "diplomacy", meaning: "외교" },
  { word: "disadvantage", meaning: "불이익" },
  { word: "disagreement", meaning: "불일치" },
  { word: "disappointment", meaning: "실망" },
  { word: "discipline", meaning: "훈련" },
  { word: "disclosure", meaning: "공개" },
  { word: "discomfort", meaning: "불편함" },
  { word: "discount", meaning: "할인" },
  { word: "discovery", meaning: "발견" },
  { word: "discrimination", meaning: "차별" },
  { word: "discussion", meaning: "토론" },
  { word: "disgrace", meaning: "불명예" },
  { word: "disorder", meaning: "무질서" },
  { word: "displacement", meaning: "이동" },
  { word: "display", meaning: "전시" },
  { word: "disposal", meaning: "처분" },
  { word: "dispute", meaning: "분쟁" },
  { word: "disruption", meaning: "붕괴" },
  { word: "dissatisfaction", meaning: "불만족" },
  { word: "dissolution", meaning: "해체" },
  { word: "distance", meaning: "거리" },
  { word: "distortion", meaning: "왜곡" },
  { word: "distraction", meaning: "주의산만" },
  { word: "distribution", meaning: "분배" },
  { word: "disturbance", meaning: "방해" },
  { word: "division", meaning: "분할" },
  { word: "documentation", meaning: "문서화" },
  { word: "domain", meaning: "영역" },
  { word: "donation", meaning: "기부" },
  { word: "doubt", meaning: "의심" },
  { word: "duration", meaning: "기간" },
  { word: "dynamics", meaning: "역학" },
  { word: "economy", meaning: "경제" },
  { word: "edition", meaning: "판" },
  { word: "educator", meaning: "교육자" },
  { word: "effectiveness", meaning: "효과성" },
  { word: "efficiency", meaning: "효율성" },
  { word: "effort", meaning: "노력" },
  { word: "elaboration", meaning: "정교화" },
  { word: "elimination", meaning: "제거" },
  { word: "embarrassment", meaning: "당혹감" },
  { word: "emergence", meaning: "출현" },
  { word: "emission", meaning: "배출" },
  { word: "emphasis", meaning: "강조" },
  { word: "employment", meaning: "고용" },
  { word: "empowerment", meaning: "권한부여" },
  { word: "enablement", meaning: "가능하게함" },
  { word: "encounter", meaning: "만남" },
  { word: "encouragement", meaning: "격려" },
  { word: "endeavor", meaning: "노력" },
  { word: "endorsement", meaning: "지지" },
  { word: "enforcement", meaning: "집행" },
  { word: "engagement", meaning: "참여" },
  { word: "enhancement", meaning: "향상" },
  { word: "enjoyment", meaning: "즐거움" },
  { word: "enlightenment", meaning: "계몽" },
  { word: "enrollment", meaning: "등록" },
  { word: "enterprise", meaning: "기업" },
  { word: "entertainment", meaning: "오락" },
  { word: "enthusiasm", meaning: "열정" },
  { word: "entity", meaning: "실체" },
  { word: "entrance", meaning: "입구" },
  { word: "entrepreneur", meaning: "기업가" },
  { word: "environment", meaning: "환경" },
  { word: "episode", meaning: "에피소드" },
  { word: "equality", meaning: "평등" },
  { word: "equipment", meaning: "장비" },
  { word: "equivalent", meaning: "등가물" },
  { word: "error", meaning: "오류" },
  { word: "escape", meaning: "탈출" },
  { word: "establishment", meaning: "설립" },
  { word: "estimate", meaning: "추정" },
  { word: "evaluation", meaning: "평가" },
  { word: "evolution", meaning: "진화" },
  { word: "examination", meaning: "시험" },
  { word: "example", meaning: "예시" },
  { word: "exception", meaning: "예외" },
  { word: "exchange", meaning: "교환" },
  { word: "excitement", meaning: "흥분" },
  { word: "exclusion", meaning: "배제" },
  { word: "excuse", meaning: "변명" },
  { word: "execution", meaning: "실행" },
  { word: "exemption", meaning: "면제" },
  { word: "exercise", meaning: "운동" },
  { word: "exhaustion", meaning: "고갈" },
  { word: "exhibit", meaning: "전시품" },
  { word: "existence", meaning: "존재" },
  { word: "exit", meaning: "출구" },
  { word: "expansion", meaning: "확장" },
  { word: "expectation", meaning: "기대" },
  { word: "expedition", meaning: "탐험" },
  { word: "expenditure", meaning: "지출" },
  { word: "expense", meaning: "비용" },
  { word: "experience", meaning: "경험" },
  { word: "experiment", meaning: "실험" },
  { word: "expert", meaning: "전문가" },
  { word: "expiration", meaning: "만료" },
  { word: "explanation", meaning: "설명" },
  { word: "exploration", meaning: "탐험" },
  { word: "explosion", meaning: "폭발" },
  { word: "export", meaning: "수출" },
  { word: "exposure", meaning: "노출" },
  { word: "expression", meaning: "표현" },
  { word: "extension", meaning: "연장" },
  { word: "extent", meaning: "범위" },
  { word: "extraction", meaning: "추출" },
  { word: "extreme", meaning: "극단" },
  { word: "fabric", meaning: "직물" },
  { word: "facility", meaning: "시설" },
  { word: "factor", meaning: "요인" },
  { word: "factory", meaning: "공장" },
  { word: "faculty", meaning: "학부" },
  { word: "failure", meaning: "실패" },
  { word: "fairness", meaning: "공정성" },
  { word: "faith", meaning: "믿음" },
  { word: "fame", meaning: "명성" },
  { word: "familiarity", meaning: "친숙함" },
  { word: "fantasy", meaning: "환상" },
  { word: "fascination", meaning: "매혹" },
  { word: "fashion", meaning: "패션" },
  { word: "fate", meaning: "운명" },
  { word: "fatigue", meaning: "피로" },
  { word: "fault", meaning: "결함" },
  { word: "favor", meaning: "호의" },
  { word: "fear", meaning: "두려움" },
  { word: "feast", meaning: "잔치" },
  { word: "feature", meaning: "특징" },
  { word: "feedback", meaning: "피드백" },
  { word: "feeling", meaning: "감정" },
  { word: "festival", meaning: "축제" },
  { word: "fiction", meaning: "소설" },
  { word: "field", meaning: "분야" },
  { word: "figure", meaning: "인물" },
  { word: "filter", meaning: "필터" },
  { word: "finance", meaning: "재정" },
  { word: "finding", meaning: "발견" },
  { word: "firmware", meaning: "펌웨어" },
  { word: "fitness", meaning: "건강" }
];

let addedCount = 0;
const startIndex = data.words.length;

for (const noun of finalNouns) {
  if (!existingWords.has(noun.word.toLowerCase())) {
    const newWord = {
      id: `nouns_${noun.word.replace(/\s+/g, '_')}_${startIndex + addedCount}`,
      word: noun.word,
      meanings: [{
        partOfSpeech: "noun",
        meaning: noun.meaning,
        examples: []
      }]
    };
    data.words.push(newWord);
    existingWords.add(noun.word.toLowerCase());
    addedCount++;
  }
}

console.log('추가된 명사 수:', addedCount);
console.log('최종 명사 수:', data.words.length);

fs.writeFileSync(filePath, JSON.stringify(data, null, 2), 'utf8');
console.log('파일 저장 완료');
