module.exports = [
  { word: 'abruptly', pronunciation: '/əˈbrʌptli/', meaning: '갑자기', example: 'He stopped abruptly.', translation: '그는 갑자기 멈췄다.' },
  { word: 'absurdly', pronunciation: '/əbˈsɜːdli/', meaning: '터무니없이', example: 'Absurdly expensive.', translation: '터무니없이 비싸다.' },
  { word: 'abundantly', pronunciation: '/əˈbʌndəntli/', meaning: '풍부하게', example: 'Abundantly clear.', translation: '매우 분명하다.' },
  { word: 'acutely', pronunciation: '/əˈkjuːtli/', meaning: '심하게, 날카롭게', example: 'Acutely aware.', translation: '예리하게 인식하다.' },
  { word: 'adamantly', pronunciation: '/ˈædəməntli/', meaning: '단호하게', example: 'Adamantly refused.', translation: '단호하게 거절했다.' },
  { word: 'adequately', pronunciation: '/ˈædɪkwətli/', meaning: '적절히', example: 'Adequately prepared.', translation: '적절히 준비되었다.' },
  { word: 'admittedly', pronunciation: '/ədˈmɪtɪdli/', meaning: '인정컨대', example: 'Admittedly, it was difficult.', translation: '인정하건대 어려웠다.' },
  { word: 'adversely', pronunciation: '/ˈædvɜːsli/', meaning: '불리하게', example: 'Adversely affected.', translation: '불리한 영향을 받다.' },
  { word: 'aggressively', pronunciation: '/əˈɡresɪvli/', meaning: '공격적으로', example: 'Aggressively marketed.', translation: '공격적으로 마케팅하다.' },
  { word: 'allegedly', pronunciation: '/əˈledʒɪdli/', meaning: '주장에 따르면', example: 'Allegedly responsible.', translation: '책임이 있다고 한다.' },
  { word: 'alternatively', pronunciation: '/ɔːlˈtɜːnətɪvli/', meaning: '그 대신에', example: 'Alternatively, you could wait.', translation: '그 대신 기다릴 수 있다.' },
  { word: 'altogether', pronunciation: '/ˌɔːltəˈɡeðər/', meaning: '완전히, 전부', example: 'Altogether different.', translation: '완전히 다르다.' },
  { word: 'amazingly', pronunciation: '/əˈmeɪzɪŋli/', meaning: '놀랍게도', example: 'Amazingly beautiful.', translation: '놀랍도록 아름답다.' },
  { word: 'amply', pronunciation: '/ˈæmpli/', meaning: '충분히', example: 'Amply demonstrated.', translation: '충분히 증명되었다.' },
  { word: 'annually', pronunciation: '/ˈænjuəli/', meaning: '매년', example: 'Reviewed annually.', translation: '매년 검토된다.' },
  { word: 'anonymously', pronunciation: '/əˈnɒnɪməsli/', meaning: '익명으로', example: 'Donated anonymously.', translation: '익명으로 기부했다.' },
  { word: 'anxiously', pronunciation: '/ˈæŋkʃəsli/', meaning: '불안하게', example: 'Waited anxiously.', translation: '불안하게 기다렸다.' },
  { word: 'apparently', pronunciation: '/əˈpærəntli/', meaning: '명백히, 보기에', example: 'Apparently, he left.', translation: '보아하니 그가 떠났다.' },
  { word: 'appreciably', pronunciation: '/əˈpriːʃəbli/', meaning: '상당히', example: 'Appreciably different.', translation: '상당히 다르다.' },
  { word: 'appropriately', pronunciation: '/əˈprəʊpriətli/', meaning: '적절하게', example: 'Dressed appropriately.', translation: '적절하게 옷을 입다.' },
  { word: 'approximately', pronunciation: '/əˈprɒksɪmətli/', meaning: '대략', example: 'Approximately 100.', translation: '대략 100개.' },
  { word: 'arbitrarily', pronunciation: '/ˌɑːbɪˈtrærəli/', meaning: '임의로', example: 'Arbitrarily chosen.', translation: '임의로 선택되었다.' },
  { word: 'arguably', pronunciation: '/ˈɑːɡjuəbli/', meaning: '논쟁의 여지가 있게', example: 'Arguably the best.', translation: '최고라고 할 수 있다.' },
  { word: 'artistically', pronunciation: '/ɑːˈtɪstɪkəli/', meaning: '예술적으로', example: 'Artistically designed.', translation: '예술적으로 디자인되었다.' },
  { word: 'assertively', pronunciation: '/əˈsɜːtɪvli/', meaning: '단호하게', example: 'Spoke assertively.', translation: '단호하게 말했다.' },
  { word: 'astonishingly', pronunciation: '/əˈstɒnɪʃɪŋli/', meaning: '놀랍게도', example: 'Astonishingly fast.', translation: '놀랍도록 빠르다.' },
  { word: 'attentively', pronunciation: '/əˈtentɪvli/', meaning: '주의 깊게', example: 'Listened attentively.', translation: '주의 깊게 들었다.' },
  { word: 'authentically', pronunciation: '/ɔːˈθentɪkəli/', meaning: '진정으로', example: 'Authentically made.', translation: '진정하게 만들어졌다.' },
  { word: 'automatically', pronunciation: '/ˌɔːtəˈmætɪkli/', meaning: '자동으로', example: 'Happens automatically.', translation: '자동으로 일어난다.' },
  { word: 'badly', pronunciation: '/ˈbædli/', meaning: '나쁘게, 몹시', example: 'Badly needed.', translation: '몹시 필요하다.' },
  { word: 'barely', pronunciation: '/ˈbeəli/', meaning: '겨우', example: 'Barely survived.', translation: '겨우 살아남았다.' },
  { word: 'bitterly', pronunciation: '/ˈbɪtəli/', meaning: '몹시, 쓰라리게', example: 'Bitterly cold.', translation: '몹시 춥다.' },
  { word: 'blissfully', pronunciation: '/ˈblɪsfəli/', meaning: '행복하게', example: 'Blissfully unaware.', translation: '행복하게 모른다.' },
  { word: 'boldly', pronunciation: '/ˈbəʊldli/', meaning: '대담하게', example: 'Boldly stated.', translation: '대담하게 말했다.' },
  { word: 'bravely', pronunciation: '/ˈbreɪvli/', meaning: '용감하게', example: 'Fought bravely.', translation: '용감하게 싸웠다.' },
  { word: 'briefly', pronunciation: '/ˈbriːfli/', meaning: '간단히', example: 'Briefly mentioned.', translation: '간단히 언급했다.' },
  { word: 'briskly', pronunciation: '/ˈbrɪskli/', meaning: '활발하게', example: 'Walked briskly.', translation: '활발하게 걸었다.' },
  { word: 'broadly', pronunciation: '/ˈbrɔːdli/', meaning: '대체로', example: 'Broadly speaking.', translation: '대체로 말하면.' },
  { word: 'brutally', pronunciation: '/ˈbruːtəli/', meaning: '잔인하게', example: 'Brutally honest.', translation: '솔직하게 말하면.' },
  { word: 'candidly', pronunciation: '/ˈkændɪdli/', meaning: '솔직하게', example: 'Speaking candidly.', translation: '솔직하게 말하면.' },
  { word: 'carefully', pronunciation: '/ˈkeəfəli/', meaning: '주의 깊게', example: 'Read carefully.', translation: '주의 깊게 읽다.' },
  { word: 'carelessly', pronunciation: '/ˈkeələsli/', meaning: '부주의하게', example: 'Acted carelessly.', translation: '부주의하게 행동했다.' },
  { word: 'casually', pronunciation: '/ˈkæʒuəli/', meaning: '대수롭지 않게', example: 'Dressed casually.', translation: '캐주얼하게 옷을 입다.' },
  { word: 'categorically', pronunciation: '/ˌkætəˈɡɒrɪkli/', meaning: '단호하게', example: 'Categorically denied.', translation: '단호하게 부인했다.' },
  { word: 'cautiously', pronunciation: '/ˈkɔːʃəsli/', meaning: '조심스럽게', example: 'Proceeded cautiously.', translation: '조심스럽게 진행했다.' },
  { word: 'ceaselessly', pronunciation: '/ˈsiːsləsli/', meaning: '끊임없이', example: 'Worked ceaselessly.', translation: '끊임없이 일했다.' },
  { word: 'centrally', pronunciation: '/ˈsentrəli/', meaning: '중심에', example: 'Centrally located.', translation: '중심에 위치하다.' },
  { word: 'characteristically', pronunciation: '/ˌkærəktəˈrɪstɪkli/', meaning: '특징적으로', example: 'Characteristically blunt.', translation: '특징적으로 무뚝뚝하다.' },
  { word: 'chiefly', pronunciation: '/ˈtʃiːfli/', meaning: '주로', example: 'Chiefly responsible.', translation: '주로 책임이 있다.' },
  { word: 'chronologically', pronunciation: '/ˌkrɒnəˈlɒdʒɪkli/', meaning: '연대순으로', example: 'Arranged chronologically.', translation: '연대순으로 배열하다.' },
  { word: 'clearly', pronunciation: '/ˈklɪəli/', meaning: '분명히', example: 'Clearly stated.', translation: '분명히 말했다.' },
  { word: 'closely', pronunciation: '/ˈkləʊsli/', meaning: '가깝게, 밀접하게', example: 'Closely related.', translation: '밀접하게 관련되어 있다.' },
  { word: 'coherently', pronunciation: '/kəʊˈhɪərəntli/', meaning: '일관성 있게', example: 'Argued coherently.', translation: '일관성 있게 주장했다.' },
  { word: 'collectively', pronunciation: '/kəˈlektɪvli/', meaning: '집단적으로', example: 'Collectively responsible.', translation: '집단적으로 책임이 있다.' },
  { word: 'comfortably', pronunciation: '/ˈkʌmftəbli/', meaning: '편안하게', example: 'Sitting comfortably.', translation: '편안하게 앉다.' },
  { word: 'comparatively', pronunciation: '/kəmˈpærətɪvli/', meaning: '비교적', example: 'Comparatively easy.', translation: '비교적 쉽다.' },
  { word: 'competently', pronunciation: '/ˈkɒmpɪtəntli/', meaning: '능숙하게', example: 'Handled competently.', translation: '능숙하게 처리했다.' },
  { word: 'comprehensively', pronunciation: '/ˌkɒmprɪˈhensɪvli/', meaning: '포괄적으로', example: 'Comprehensively covered.', translation: '포괄적으로 다루었다.' },
  { word: 'compulsively', pronunciation: '/kəmˈpʌlsɪvli/', meaning: '강박적으로', example: 'Compulsively organized.', translation: '강박적으로 정리하다.' },
  { word: 'conceivably', pronunciation: '/kənˈsiːvəbli/', meaning: '아마도', example: 'Conceivably true.', translation: '아마도 사실일 수 있다.' },
  { word: 'conclusively', pronunciation: '/kənˈkluːsɪvli/', meaning: '결정적으로', example: 'Proven conclusively.', translation: '결정적으로 증명되었다.' },
  { word: 'concurrently', pronunciation: '/kənˈkʌrəntli/', meaning: '동시에', example: 'Running concurrently.', translation: '동시에 실행되다.' },
  { word: 'conditionally', pronunciation: '/kənˈdɪʃənəli/', meaning: '조건부로', example: 'Conditionally approved.', translation: '조건부로 승인되었다.' },
  { word: 'confidently', pronunciation: '/ˈkɒnfɪdəntli/', meaning: '자신 있게', example: 'Spoke confidently.', translation: '자신 있게 말했다.' },
  { word: 'consciously', pronunciation: '/ˈkɒnʃəsli/', meaning: '의식적으로', example: 'Consciously chosen.', translation: '의식적으로 선택했다.' },
  { word: 'consecutively', pronunciation: '/kənˈsekjʊtɪvli/', meaning: '연속적으로', example: 'Won consecutively.', translation: '연속으로 이겼다.' },
  { word: 'considerably', pronunciation: '/kənˈsɪdərəbli/', meaning: '상당히', example: 'Considerably higher.', translation: '상당히 높다.' },
  { word: 'consistently', pronunciation: '/kənˈsɪstəntli/', meaning: '일관되게', example: 'Consistently performed.', translation: '일관되게 수행했다.' },
  { word: 'conspicuously', pronunciation: '/kənˈspɪkjuəsli/', meaning: '눈에 띄게', example: 'Conspicuously absent.', translation: '눈에 띄게 없다.' },
  { word: 'constructively', pronunciation: '/kənˈstrʌktɪvli/', meaning: '건설적으로', example: 'Respond constructively.', translation: '건설적으로 대응하다.' },
  { word: 'continuously', pronunciation: '/kənˈtɪnjuəsli/', meaning: '계속해서', example: 'Improved continuously.', translation: '계속해서 개선되다.' },
  { word: 'convincingly', pronunciation: '/kənˈvɪnsɪŋli/', meaning: '설득력 있게', example: 'Argued convincingly.', translation: '설득력 있게 주장했다.' },
  { word: 'cooperatively', pronunciation: '/kəʊˈɒpərətɪvli/', meaning: '협력적으로', example: 'Worked cooperatively.', translation: '협력적으로 일했다.' },
  { word: 'correspondingly', pronunciation: '/ˌkɒrɪˈspɒndɪŋli/', meaning: '상응하게', example: 'And correspondingly.', translation: '그에 상응하게.' },
  { word: 'critically', pronunciation: '/ˈkrɪtɪkli/', meaning: '비판적으로, 심각하게', example: 'Critically important.', translation: '매우 중요하다.' },
  { word: 'crucially', pronunciation: '/ˈkruːʃəli/', meaning: '결정적으로', example: 'Crucially, he agreed.', translation: '결정적으로 그가 동의했다.' },
  { word: 'cunningly', pronunciation: '/ˈkʌnɪŋli/', meaning: '교활하게', example: 'Cunningly designed.', translation: '교활하게 설계되었다.' },
  { word: 'curiously', pronunciation: '/ˈkjʊəriəsli/', meaning: '호기심으로', example: 'Curiously enough.', translation: '신기하게도.' },
  { word: 'currently', pronunciation: '/ˈkʌrəntli/', meaning: '현재', example: 'Currently working.', translation: '현재 일하고 있다.' },
  { word: 'customarily', pronunciation: '/ˈkʌstəmərəli/', meaning: '관례적으로', example: 'Customarily done.', translation: '관례적으로 행해진다.' },
  { word: 'daily', pronunciation: '/ˈdeɪli/', meaning: '매일', example: 'Updated daily.', translation: '매일 업데이트된다.' },
  { word: 'daringly', pronunciation: '/ˈdeərɪŋli/', meaning: '대담하게', example: 'Daringly original.', translation: '대담하게 독창적이다.' },
  { word: 'decisively', pronunciation: '/dɪˈsaɪsɪvli/', meaning: '결정적으로', example: 'Acted decisively.', translation: '결정적으로 행동했다.' },
  { word: 'deeply', pronunciation: '/ˈdiːpli/', meaning: '깊이', example: 'Deeply concerned.', translation: '깊이 우려하다.' },
  { word: 'defensively', pronunciation: '/dɪˈfensɪvli/', meaning: '방어적으로', example: 'Responded defensively.', translation: '방어적으로 대응했다.' },
  { word: 'definitely', pronunciation: '/ˈdefɪnətli/', meaning: '확실히', example: 'Definitely true.', translation: '확실히 사실이다.' },
  { word: 'deliberately', pronunciation: '/dɪˈlɪbərətli/', meaning: '의도적으로', example: 'Deliberately ignored.', translation: '의도적으로 무시했다.' },
  { word: 'delicately', pronunciation: '/ˈdelɪkətli/', meaning: '섬세하게', example: 'Delicately handled.', translation: '섬세하게 다루었다.' },
  { word: 'demonstrably', pronunciation: '/dɪˈmɒnstrəbli/', meaning: '명백히', example: 'Demonstrably false.', translation: '명백히 거짓이다.' },
  { word: 'densely', pronunciation: '/ˈdensli/', meaning: '밀집하여', example: 'Densely populated.', translation: '인구가 밀집되어 있다.' },
  { word: 'desperately', pronunciation: '/ˈdespərətli/', meaning: '필사적으로', example: 'Desperately needed.', translation: '절실히 필요하다.' },
  { word: 'diligently', pronunciation: '/ˈdɪlɪdʒəntli/', meaning: '부지런히', example: 'Worked diligently.', translation: '부지런히 일했다.' },
  { word: 'directly', pronunciation: '/dɪˈrektli/', meaning: '직접적으로', example: 'Directly responsible.', translation: '직접적으로 책임이 있다.' },
  { word: 'distinctly', pronunciation: '/dɪˈstɪŋktli/', meaning: '뚜렷이', example: 'Distinctly different.', translation: '뚜렷이 다르다.' },
  { word: 'drastically', pronunciation: '/ˈdræstɪkli/', meaning: '극적으로', example: 'Drastically changed.', translation: '극적으로 변했다.' },
  { word: 'duly', pronunciation: '/ˈdjuːli/', meaning: '정당하게', example: 'Duly noted.', translation: '적절히 기록되었다.' },
  { word: 'dynamically', pronunciation: '/daɪˈnæmɪkli/', meaning: '역동적으로', example: 'Dynamically changing.', translation: '역동적으로 변하다.' }
];
